/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        iPhone iPhone = new iPhone("iphonX", "white", "iPhone");
        iPhone.callMessage("I'm working");
        Android android = new Android("nova3", "white", "Huawei");
        android.callMessage("I'm breaking");
        iPhone.printMessage();
        Custom custom=new Custom("Laura",iPhone);
        custom.setPhone(android);
    }
}
